### ISSUE TITLE
cannot reference from file  myfile.md to anchor in mmmm/anotherfile.md

### ISSUE THREAD

**Issue by maxlapshin** [foliant-docs/foliantcontrib.superlinks#1]
If source file and referenced have some common letters in the beginning of path then usage of os.path.commonprefix will put these letters into common path and search will be done in catalog named `m`  (common prefix)

Should use os.path.commonpath instead of it.

https://stackoverflow.com/questions/21498939/how-to-circumvent-the-fallacy-of-pythons-os-path-commonprefix

**Comment by Vanderhoof** [comment]
Thank you for bug report!
Done in 1.0.9
